name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: benfiola
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: release
        uses: go-semantic-release/action@v1
        with:
          force-bump-patch-version: true
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
